config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resource :theme, :controller => 'disguise/themes'
    resources :domain_themes, :controller => 'disguise/domain_themes'
  end
end

app/models/domain_theme.rb
class DomainTheme < ActiveRecord::Base
  
  validates_presence_of :name, :uri
  
  class << self
    def use_domain_themes?
      Disguise.configuration.use_domain_for_themes
    end
  
    def get_theme(request)
      domain_theme = get_domain_theme(request)
      domain_theme.blank? ? nil : Theme.new(:name => domain_theme.name)
    end
    
    def get_domain_theme(request)
      self.find_by_uri(request.host)
    end
  end
  
end

app/models/theme.rb
class Theme < ActiveRecord::Base

  def locales
    Dir[ File.join(::Rails.root.to_s, 'themes', self.name, 'locales', '*.{rb,yml}') ]
  end
  
  # This method will iterate through all available themes in the theme directory
  # and then return an array of all themes as well as the currently selected theme
  # as a hash in the format:
  #  {:name => theme_name, :preview_image => image, :description => description}
  # This can then be used by the view layer to show the user a list of available themes
  # along with a preview image.
  def self.available_themes(selected_theme)
    themes = []
    theme_path = Disguise.configuration.theme_full_base_path
    current_theme = nil
    
    Dir.glob("#{theme_path}/*").each do |theme_directory|
      if File.directory?(theme_directory)
        theme_name = File.basename(theme_directory)

        image = Dir.glob(File.join(::Rails.root.to_s, 'public', 'images', theme_name, 'preview.*')).first || File.join('/', 'images', 'no_preview.gif')
        image = image.gsub(File.join(::Rails.root.to_s, 'public'), '')

        description = ''
        description_file = File.join(theme_directory, 'description.txt')
        if File.exist?(description_file)
          f = File.new(description_file, "r")
          description = f.read
          f.close
        end

        theme = {:name => theme_name, :preview_image => image, :description => description}
        themes << theme

        current_theme = theme if selected_theme.name == theme_name
      end
    end

    [current_theme, themes]
  end

end

app/controllers/admin/disguise/domain_themes_controller.rb
class Admin::Disguise::DomainThemesController < ApplicationController
  unloadable

  def create
    @domain_theme = DomainTheme.new(params[:domain_theme])
    if !@domain_theme.save
      flash[:notice] = t('disguise.error_creating_domain_theme', :error => @domain_theme.errors.full_messages.to_sentence)
    else
      flash[:notice] = t('disguise.theme_updated')
    end
    respond_to do |format|
      format.html { redirect_to edit_admin_theme_path }
    end
  end
  
  def update
    @domain_theme = DomainTheme.find_by_name(params[:domain_theme][:name])
    @domain_theme.update_attributes!(params[:domain_theme])
    respond_to do |format|
      flash[:notice] = t('disguise.theme_updated')
      format.html { redirect_to edit_admin_theme_path }
    end
  end

  def destroy
    @domain_theme = DomainTheme.find(params[:id])
    @domain_theme.destroy
    respond_to do |format|
      flash[:notice] = t('disguise.uri_deleted')
      format.html { redirect_to edit_admin_theme_path }
    end
  end
  
end

app/controllers/admin/disguise/themes_controller.rb
class Admin::Disguise::ThemesController < ApplicationController
  unloadable

  before_filter :get_theme

  def edit
    @current_theme, @themes = Theme.available_themes(@theme)
    @domain_themes = {}
    DomainTheme.all.each{ |d| @domain_themes[d.name] = @domain_themes[d.name].blank? ? [d] : @domain_themes[d.name] << d }
    if @themes.empty?
      respond_to do |format|
        format.html { render :template => 'admin/themes/no_themes' }
      end
    else
      respond_to do |format|
        format.html { render :template => 'admin/themes/edit' }
      end
    end
  end

  def update
    @theme.update_attributes!(params[:theme])
    respond_to do |format|
      if @theme.name.blank?
        flash[:notice] = t('disguise.theme_removed')
      else
        flash[:notice] = t('disguise.theme_updated')
      end
      format.html { redirect_to edit_admin_theme_path }
    end
  end

  private
    def get_theme
      @theme = Theme.first || Theme.create
    end

end

app/views/admin/themes/_theme.html.erb
<div class="theme-block box">
  <h3><%= theme[:name] %></h3>
  <%= form_for @theme, :url => admin_theme_path, :html => { :method => :put } do |f| -%>
  	<%= f.hidden_field :name, :value => theme[:name] %>
  	<%= image_submit_tag theme[:preview_image], :id => "#{theme[:name].parameterize}", :name => "#{theme[:name].parameterize}" %>
  	<%= theme[:description] %>
  <% end -%>
  <% if DomainTheme.use_domain_themes? -%>
    <% domain_theme = DomainTheme.new(:name => theme[:name]) %>
    <%= form_for [:admin, domain_theme] do |f| -%>
    	<%= f.hidden_field :name %>
    	<%= f.label t('disguise.theme_uri_label') %>
    	<%= f.text_field :uri %>
      <%= submit_tag t('disguise.add_uri') %>
    <% end -%>
  <% end -%>
  <% if !@domain_themes[theme[:name]].blank? %>
    <p class="theme-information"><%= t('disguise.uris_title') %></p>
    <ul class="theme-list">
      <% @domain_themes[theme[:name]].each do |domain_theme| -%>
        <li>
          <%= form_for [:admin, domain_theme], :html => { :method => :delete } do |f| -%>
            <%= domain_theme.uri %>
            <%= submit_tag t('disguise.delete_uri') %>
          <% end -%>
        </li>
      <% end -%>
    </ul>
  <% end -%>
</div>

app/views/admin/themes/edit.html.erb
<h1><%= t('disguise.set_theme') %></h1>
<div id="current-theme">
  <% if DomainTheme.use_domain_themes? -%>
    <h2><%= t('disguise.use_domain_themes') %></h2>
  <% else -%>
    <h2><%= t('disguise.name_theme') %></h2>
    <% if @current_theme -%>
      <%= render :partial => 'admin/themes/theme', :object => @current_theme %>      
      <%= form_for @theme, :url => admin_theme_path, :html => { :method => :put } do |f| -%>
        <%= f.hidden_field :name, :value => '' %>
        <%= submit_tag t('disguise.remove_all_themes'), :id => 'remove_all_themes', :name => 'remove_all_themes' %>
      <% end -%>
    <% else -%>
      <%= t('disguise.no_current_theme') %>
    <% end -%>
    <h2><%= t('disguise.activate_theme_message') %></h2>
  <% end -%>
</div>
<% if !@theme.blank? && @theme.errors.any? -%>
  <ul>
    <% @theme.errors.full_messages.each do |msg| -%>
      <li><%= msg %></li>
    <% end -%>
  </ul>
<% end -%>

<%= render :partial => 'admin/themes/theme', :collection => @themes %>

app/views/admin/themes/no_themes.html.erb
<div id="theme-instructions">
  <p><%= t('disguise.no_themes_message') %></p>
  <pre>./script/generate theme theme_name</pre>
</div>